# Generated by Django 2.2.5 on 2021-11-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20211102_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='room',
        ),
    ]
